Repository Kllami/DelBaraticoProyectoBD, pull requests merged in 2021-11, with the labels that each got.

#10 arreglo foreign key del numero de caja en tabla factura
  Entregables/III_entregable_BD_II.sql
Labels: bug, enhancement

#13 unique constraints of EAN and autoincremental id in every table
  Entregables/III_entregable_BD_II.sql
Labels: bug

#17 Ventana ventas
  DelBaratico/src/Main.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/JdbcUtil.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/UsuarioDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Model.java
  DelBaratico/src/main/java/cr/una/delbaratico/service/Service.java
  DelBaratico/src/main/java/cr/una/delbaratico/service/ServiceController.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/BitacorasView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/BitacorasView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/CajaView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/CajaView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/FacturasView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/FacturasView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/LoginView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/LoginView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/iniciarsesion/IniciarSesionController.java
Labels: MVS, VentanaHome, Login, Fix

#24 Modificando tamaño home
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.java
Labels: bug, Fix

#25 Fresco peso
  DelBaratico/src/main/java/cr/una/delbaratico/dao/AreaDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/AuditoriaDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/CajaDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/DetalleFrescoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/DetalleSecoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/FacturaDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/FrescoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/SecoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/UsuarioDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Model.java
  DelBaratico/src/main/java/cr/una/delbaratico/service/ServiceController.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/CajaView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/CajaView.java
  Entregables/III_entregable_BD_II.sql
Labels: Fix, fresco

#26 BitacoraVista
  DelBaratico/DelBaratico.iml
  DelBaratico/src/main/java/cr/una/delbaratico/dao/AuditoriaDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/BitacorasView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/BitacorasView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/CajaView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.java
  Entregables/III_entregable_BD_II.sql
  Entregables/InsercionesBBDD.sql
Labels: BitácoraView

#29 Ventana inventario v1
  DelBaratico/src/main/java/cr/una/delbaratico/dao/AreaDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/FrescoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/JdbcUtil.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/SecoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Fresco.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Model.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Producto.java
  DelBaratico/src/main/java/cr/una/delbaratico/service/ServiceController.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/CajaView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/VentanaAgregarEditar.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/VentanaAgregarEditar.java
  Entregables/IV_entregable_BD_II.sql
Labels: ventanaInventario

#30 Ventana inventario v2
  DelBaratico/src/main/java/cr/una/delbaratico/dao/AreaDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/FrescoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/SecoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Fresco.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Model.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Producto.java
  DelBaratico/src/main/java/cr/una/delbaratico/model/Seco.java
  DelBaratico/src/main/java/cr/una/delbaratico/service/ServiceController.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/CajaView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/LoginView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/LoginView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/VentanaAgregarEditar.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/VentanaEliminar.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/VentanaEliminar.java
Labels: ventanaInventario

#33 grants a los gerentes de area para consultar tablas: area, secos y fr…
  DelBaratico/DelBaratico.iml
  Entregables/III_entregable_BD_II.sql
  Entregables/IV_entregable_BD_II.sql
Labels: bug

#39 Ventana inventario
  DelBaratico/src/main/java/cr/una/delbaratico/dao/FrescoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/SecoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/BitacorasView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/BitacorasView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/FacturasView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/FacturasView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/RegistroVentasView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/RegistroVentasView.java
  Entregables/IV_entregable_BD_II.sql
Labels: base de datos, FrescoDAO, SecoDAO, Ventanas, Fixes

#44 Documentos de pruebas y fixes
  DelBaratico/src/main/java/cr/una/delbaratico/dao/FrescoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/JdbcUtil.java
  DelBaratico/src/main/java/cr/una/delbaratico/dao/SecoDAO.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/BitacorasView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/FacturasView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/HomeView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/InventarioView.java
  DelBaratico/src/main/java/cr/una/delbaratico/view/RegistroVentasView.form
  DelBaratico/src/main/java/cr/una/delbaratico/view/RegistroVentasView.java
  Documento de Pruebas.docx
Labels: Fixes, documento de pruebas
